document.write("<h2>Rules for Naming JS Variables</h2>");
document.write("Variable names can only contain Letter, Numbers,");
document.write(" $ and _ .");
document.write("For example : $my_1stVariable.");
document.write("<br>");
document.write("Variables must begin with a Letter, $ or _ .");
document.write("For example $name, _name or name");
document.write("<br>");
document.write("Variable names are case Sensitive");
document.write("<br>");
document.write("Variable names should not be JS Keywords");